apiVersion: codefresh.io/v1beta2
kind: Product
metadata:
  name: product-1
spec:
  promotionTemplate:
    versionSource:
      file: Chart.yaml
      jsonPath: $.version
    promotion:
      Chart.yaml:
        jsonPaths:
          - $.appVersion
  concurrency: queue
