apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cf-gitops-runtime
  labels:
    codefresh.io/entity: runtime
    codefresh.io/internal: 'true'
spec:
  project: cf-runtime-app-project
  source:
    repoURL: https://github.com/Alina-onprem/shared-repo-2.10.git
    targetRevision: HEAD
    path: resources/test-runtime/chart
    helm:
      releaseName: cf-gitops-runtime
  destination:
    namespace: test-runtime
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
